version: '3.8'

services:

  app:
    build: .
    command: poetry run uvicorn src.book_keeper:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8004:8000
    environment:
      - BOOK_KEEPER_DB__URL=postgresql+asyncpg://postgres:postgres@db:5432/bookkeeper
    depends_on:
      - db

  db:
    image: postgres:15.3
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookkeeper
